version: '3.8'

services:
  unravel:
    build: .
    container_name: unravel-persistent
    ports:
      - "3007:3006"
    environment:
      # Production API keys (optional - can be set via settings UI)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - GROK_API_KEY=${GROK_API_KEY:-}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
      - JINA_API_KEY=${JINA_API_KEY:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - PORT=3006
    volumes:
      # Persistent storage for settings and custom patterns
      - unravel_config:/app/config
      # Optional: Mount local patterns directory for development
      # - ./patterns:/app/patterns:ro
    restart: unless-stopped
    networks:
      - homelab
      - unravel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  unravel_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config

networks:
  homelab:
    external: true
    name: homelab_homelab
  unravel-network:
    external: true
    name: unravel_unravel-network